name: ecommerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2        # ✅ GARDER - Pour photos/vidéos
  file_picker: ^10.2.0       # ✅ GARDER - Pour documents
  path_provider: ^2.1.1      # ✅ GARDER - Pour chemins fichiers
  socket_io_client: 1.0.2    # ✅ GARDER - Pour WebSocket
  web_socket_channel: ^3.0.3 # ✅ GARDER - Pour WebSocket

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/hero/